eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka Server
    fetch-registry: true       # Enable fetching the registry from the Eureka server
    register-with-eureka: true # Enable registration with the Eureka server
  instance:
    prefer-ip-address: true     # Use IP address for registration instead of hostname
